Ext.define('Admin.view.template.Templates', {
    extend: 'Ext.panel.Panel',
    xtype: '_templates',
    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    padding: 10,
    autoScroll: true,
    overflowY: 'scroll',
    items: [{
            html: 'Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> Appli <br> cations <br> where <br> I <br> am <br> a <br> collaborator <br> '
        }]
});
